### PR TITLE
Feat/cmc 1651: MP view and respond to defence RPA Handed Off Stays Online

### PR DESCRIPTION
**Pull request by sankaviv1**
### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CMC-1651

### Change description ###

- add MP full defence response to RPA json

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Review by bhssamray — COMMENTED** [review]
Approved.

**Review by Gareth40343 — COMMENTED** [review]
Approved

**Comment by sankaviv1** [comment]
Reopening for QA

**Review by akriti-hmcts — APPROVED** [review]

**Review by Gareth40343 — APPROVED** [review]

**Review by bhssamray — APPROVED** [review]

**Review by HarryH96 — APPROVED** [review]

**Comment by sankaviv1** [comment]
these changes have already been merged with https://github.com/hmcts/civil-service/pull/784/

**Pull request closed without merging**
