### PR TITLE
CIV-10143 Update GA Dismissal Doc template

### PR DESCRIPTION
**Pull request by karthick-mohanasundaram-HMCTS**
**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/CIV-10143

### Change description ###

Update Ga dismissal order template

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Comment by karthick-mohanasundaram-HMCTS** [comment]
image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
http://localhost:3333/cases/case-details/1695804264807846#Application

**Comment by karthick-mohanasundaram-HMCTS** [comment]
- [ ] Change date format

**Comment by karthick-mohanasundaram-HMCTS** [comment]
image

image

**Comment by karthick-mohanasundaram-HMCTS** [comment]
image

image

**Review by drummondjm — APPROVED** [review]

**Comment by karthick-mohanasundaram-HMCTS** [comment]
image

**Pull request closed without merging**
