### PR TITLE
CIV-14752 Manage stay changes

### PR DESCRIPTION
**Pull request by kannan-v-hmcts**
PR for https://tools.hmcts.net/jira/browse/CIV-14752

### CODE REVIEW

**Review by ss-evoco — CHANGES_REQUESTED** [review]
I think we need a new feature flag for this. My understanding is we are splitting out each of the CW events into their own releases ? Similar too : https://github.com/hmcts/civil-service/pull/5480/files#diff-afe5cc338e2cf018d80d833a45f1f3f8fea6dfafe813376c627b5ffbc88f2232

**Review by ss-evoco — CHANGES_REQUESTED** [review]
I think this needs to be under its own feature flag as all the CW events are being released under their own features, similar too : https://github.com/hmcts/civil-service/pull/5480/files#diff-afe5cc338e2cf018d80d833a45f1f3f8fea6dfafe813376c627b5ffbc88f2232

**Comment by kannan-v-hmcts** [comment]
> I think we need a new feature flag for this. My understanding is we are splitting out each of the CW events into their own releases ? Similar too : https://github.com/hmcts/civil-service/pull/5480/files#diff-afe5cc338e2cf018d80d833a45f1f3f8fea6dfafe813376c627b5ffbc88f2232

Hi @ss-evoco I discussed this with @m-meulendijks-v1 and was told that only amend Bundle + move document + manage document was collected under the new amendBundle feature toggle. Stay, dismiss, manage stay etc will all be under existing caseWorker events

**Review by dharmendrak — DISMISSED** [review]

**Review by dharmendrak — DISMISSED** [review]

**Comment by m-meulendijks-v1** [comment]
> > I think we need a new feature flag for this. My understanding is we are splitting out each of the CW events into their own releases ? Similar too : https://github.com/hmcts/civil-service/pull/5480/files#diff-afe5cc338e2cf018d80d833a45f1f3f8fea6dfafe813376c627b5ffbc88f2232
> 
> Hi @ss-evoco I discussed this with @m-meulendijks-v1 and was told that only amend Bundle + move document + manage document was collected under the new amendBundle feature toggle. Stay, dismiss, manage stay etc will all be under existing caseWorker events

Yes, Kannan's understanding is correct, see the feature toggle ticket I am working on defines future caseworker events (such as manage stay) as belonging to release 2:
image

**Review by ss-evoco — DISMISSED** [review]

**Review by m-meulendijks-v1 — APPROVED** [review]

**Review by ss-evoco — APPROVED** [review]

**Pull request merged**
